spring:
  datasource:
    #    url: jdbc:h2:mem:voting TIME ZONE=UTC;
    url: jdbc:h2:./db/voting;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

#  jackson.time-zone: UTC

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true
    force: true

springdoc.swagger-ui.path: /



