spring:
  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true